### PR TITLE
Print error to howdoyou buffer

### PR DESCRIPTION
**Pull request by Boruch-Baum**
+ Completes TODO formerly on line ~270

+ Renames function howdoyou--print-waiting-message to
  howdoyou--print-message and makes msg argument mandatory

### CODE REVIEW

**Comment by thanhvg** [comment]
I just checked out your PR. Generally I like the change but it comes with some inconvenience. The error message now is multi line and when it's printed to the minibuffer it causes a change in the window side for a short time. This could be annoying. 

Originally, my idea was to print the error to howdoyou buffer, not minibuffer. But I can see you change can benefit debugging. So I propose two options to this PR:

- a debug variable, if `t` then errors  will be verbose like this PR is doing otherwise error printing will be kept as current, default value is `nil`
- or print error to howdoyou buffer.

Either option is fine with me.

Thanks

**Comment by Boruch-Baum** [comment]
On 2021-08-08 12:45, thanhvg wrote:
>    The error message now is multi line and when it's printed to the
>    minibuffer it causes a change in the window side for a short time.
>    This could be annoying.

How about not printing the message to the mini-buffer at all?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
Uh, Please ignore my last message. I may have been confused. Something
seemed wrong about it so I looked at the code again, and ...

On 2021-08-08 12:45, thanhvg wrote:
>    I just checked out your PR. Generally I like the change but it comes
>    with some incontinence. The error message now is multi line and when
>    it's printed to the minibuffer it causes a change in the window side
>    for a short time. This could be annoying.

Is that happening? I don't see where in the code that I'm outputting
anything to the mini-buffer. Everything new that I see is going to the
output buffer via 'insert'. Only output that was already using 'message'
continues to do so.


--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by thanhvg** [comment]
Let me double check again later. Thanks

**Comment by Boruch-Baum** [comment]
On 2021-08-09 08:12, thanhvg wrote:
>    Let me double check again later. Thanks

My memory is that the way I tested this was to change the google url to
something else. For your testing ,you could use any other url or even a
garbage string.

Also, please don't forget the other two PR's that I posted, when you get
the chance.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by thanhvg** [comment]
Thanks and sorry for the misfire.

**Pull request merged**
